### ISSUE TITLE
Input tuple error

### ISSUE THREAD

**Issue by V-Catherine** [IARCbioinfo/abra-nf#15]
The pipeline does not work anymore when we don't have junctions files (which are specific to RNAseq data):
"Input tuple does not match input set cardinality declared by process `abra`"
The issue is at the input of the abra process : "set bam_tag, file(bam), file(bai), file(junctions) from bam_bai". There should be an alternative like "set bam_tag, file(bam), file(bai) from bam_bai" for DNA seq bams

**Comment by nalcala** [comment]
Solved by https://github.com/IARCbioinfo/abra-nf/commit/396de2132a2e515e39b550a858674bf101a8cd43
